#pragma once

#define rwRASTERTYPEZBUFFER 0x01
#define rwRASTERTYPETEXTURE 0x04
#define rwRASTERTYPECAMERATEXTURE 0x05

#define rwCAMERACLEARIMAGE 0x1
#define rwCAMERACLEARZ 0x2
#define rwRENDERSTATETEXTURERASTER 1
#define rwRENDERSTATEFOGENABLE 0xE
#define rwRENDERSTATESRCBLEND 0xA
#define rwRENDERSTATEDESTBLEND 0xB
#define rwRENDERSTATECULLMODE 0x14
#define rwRENDERSTATETEXTUREFILTER 9
#define rwRENDERSTATEVERTEXALPHAENABLE 0xC